# Generated by Django 4.1.7 on 2023-03-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('lat', models.TextField()),
                ('lon_175_180W', models.IntegerField()),
                ('lon_170_175W', models.IntegerField()),
                ('lon_165_170W', models.IntegerField()),
                ('lon_160_165W', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
