# Generated by Django 4.1.7 on 2023-03-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatology_stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_130_135W',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_135_140W',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_140_145W',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_145_150W',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_150_155W',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_155_160W',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='year_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='climatology_stories.year'),
            preserve_default=False,
        ),
    ]
