# Generated by Django 4.1.7 on 2023-03-23 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatology_stories', '0002_year_climate_lon_130_135w_climate_lon_135_140w_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climate',
            name='lon_130_135W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_135_140W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_140_145W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_145_150W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_150_155W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_155_160W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_160_165W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_165_170W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_170_175W',
        ),
        migrations.RemoveField(
            model_name='climate',
            name='lon_175_180W',
        ),
    ]
