# Generated by Django 4.1.7 on 2023-03-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatology_stories', '0003_remove_climate_lon_130_135w_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climate',
            name='year_ID',
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_130_135W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_135_140W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_140_145W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_145_150W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_150_155W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_155_160W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_160_165W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_165_170W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_170_175W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='climate',
            name='lon_175_180W',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
