# Generated by Django 4.1.7 on 2023-03-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climatology_stories', '0004_remove_climate_year_id_climate_lon_130_135w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='year_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='climatology_stories.year'),
            preserve_default=False,
        ),
    ]
