
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-75%lly($0+1jnb8fy$8wp)@se*v1#uws&2=7p*=1pd&9v5+a_a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ 'https://groupindia.onrender.com','groupindia.onrender.com', '127.0.0.1', 'beyondlaura-exceptvisa-8000.codio-box.uk', 'localhost', 'spendminimum-stadiumjaguar-8000.codio-box.uk', 'politicpermit-freedompastel-8000.codio-box.uk', 'opinionwave-octaviagordon-8000.codio-box.uk', 'ingridinfo-designlogo-8000.codio-box.uk', 'salsanurse-arthurcosmos-8000.codio-box.uk', 'infohavana-maydaypenguin-8000.codio-box.uk', 'rajapicture-comedystatic-8000.codio-box.uk', 'miketopic-rentgraph-8000.codio-box.uk','rajapicture-comedystatic-8000.codio-box.uk']

CSRF_TRUSTED_ORIGINS = [ 'https://groupindia.onrender.com', 'http://127.0.0.1', 'https://beyondlaura-exceptvisa-8000.codio-box.uk', 'https://spendminimum-stadiumjaguar-8000.codio-box.uk', 'https://politicpermit-freedompastel-8000.codio-box.uk', 'https://opinionwave-octaviagordon-8000.codio-box.uk',
                        'https://ingridinfo-designlogo-8000.codio-box.uk', 'https://salsanurse-arthurcosmos-8000.codio-box.uk', 'https://infohavana-maydaypenguin-8000.codio-box.uk', 'https://miketopic-rentgraph-8000.codio-box.uk', 'https://rajapicture-comedystatic-8000.codio-box.uk','https://rajapicture-comedystatic-8000.codio-box.uk/']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'climatology_stories.apps.ClimatologyStoriesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['common'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"